### ISSUE TITLE
Have a --no-run option

### ISSUE THREAD

**Issue by nfachan** [meticulous-software/meticulous#117]

**Comment by bobbobbio** [comment]
what would this option do? the cargo one seems to build test binaries but not run anything, would this be the same idea?

**Comment by nfachan** [comment]
Yeah, upon more reflection, I'm not sure this makes sense. I think this is just the same as `--list-tests`. Maybe we could add a `build` option at some point that would be just like `--list-tests` in that it would build all of the binaries, but wouldn't run them or print any output.
