### ISSUE TITLE
Provide a status bar for outstanding jobs

### ISSUE THREAD

**Issue by nfachan** [meticulous-software/meticulous#35]
This should include the number of jobs in the following states:
- Done. For unit tests, this should be broken down into passed, failed, and error.
- Executing. This means the job is at the worker.
- Queued. This means the job is sitting at the broker waiting to be assigned to a worker.
- Waiting on artifact. This means the job is blocked on the broker getting at least one artifact.
- Pending. This means the job either hasn't been sent to the broker yet, or the client hasn't received an acknowledgement yet.

**Comment by bobbobbio** [comment]
> Pending. This means the job either hasn't been sent to the broker yet, or the client hasn't received an acknowledgement yet.
There is no state for this yet, I'm not sure its worth pursing at this time, we can always come back to it.
